# Generated by Django 5.0.7 on 2024-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_careerform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerform',
            name='resume_or_portfolio',
        ),
    ]
