# Generated by Django 5.0.7 on 2024-12-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_careerform_resume_or_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerform',
            name='resume_or_portfolio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='careerform',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_forms', to='mainapp.userprofile'),
        ),
    ]
